### ISSUE TITLE
Containerize Application

### ISSUE THREAD

**Issue by Vishal1297** [Vishal1297/contacts-manager#4]
### To-do

- [x] Create Dockerfile
- [x] Create app image
- [ ] Push image to docker hub

**Comment by HattoriHenzo** [comment]
@Vishal1297 Let me work on it.

**Comment by Vishal1297** [comment]
> @Vishal1297 Let me work on it.

@HattoriHenzo Okay, go ahead

create Dockerfile & push on branch named "feature/branchName"
